### ISSUE TITLE
Secure postgres configuration

### ISSUE THREAD

**Issue by indigo423** [devynspencer/ansible-opennms#1]
The current configuration sets authentication to trust which means PostgreSQL is completely open from localhost without authentication. The configuration should be set to md5 with local authentication. A more secure setup procedure is described here:

http://docs.opennms.org/opennms/branches/develop/guide-install/guide-install.html#gi-install-opennms-rhel-prepare-pg

**Comment by devynspencer** [comment]
Thanks Ronny! This was laziness (and lack of hand-configuring PostgreSQL for a while) on my part, but without a disclaimer in the README, this should definitely be tightened up. - Consider it done!

:)
