### ISSUE TITLE
Database admin user instead of opennms user

### ISSUE THREAD

**Issue by indigo423** [devynspencer/ansible-opennms#2]
In the ``opennms-datasources.xml`` template the ``opennms_database_admin`` should be used instead of the ``opennms_database_name`` user which is defined in the [default variables](https://github.com/devynspencer/ansible-opennms/blob/9e157097c9bd023232ea442e53412087798fdb6f/templates/opennms-datasources.xml.j2#L26)

**Comment by devynspencer** [comment]
I remember the context for some of what stopped me from finishing this now. Our config example for `opennms-datasources.xml` has the following:

```xml
<jdbc-data-source name="opennms"
                    database-name="opennms"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/opennms"
                    user-name="** YOUR-OPENNMS-USERNAME **"
                    password="** YOUR-OPENNMS-PASSWORD **" />

<jdbc-data-source name="opennms-admin"
                    database-name="template1"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/template1"
                    user-name="** YOUR-OPENNMS-USERNAME **"
                    password="** YOUR-OPENNMS-PASSWORD **" />
```

What is the second datasource referring to above?

- As far as I can tell it's referring to a second, admin-specific database (perhaps to track admin related ... data).

- Specifically, my guess for the above is that it's using both a created database (`opennms`, as well as whatever the default database created by PostgreSQL is, i.e. `template1`.

Do I have any of that right?

If so, I'll actually need to create an additional `postgresql_db` task to properly implement *both* databases, i.e:

```ansible
- name: postgresql | ensure database is created
  postgresql_db: >
    name={{ opennms_admin_database_name }}
    login_host=localhost
    state=present

- name: opennms | configure user access to database
  postgresql_user: >
    db={{ opennms_admin_database_name }}
    name={{ opennms_admin_database_user }}
    password={{ opennms_admin_database_pass }}
    priv=ALL
    state=present
```
